--- #YAML:1.0
name:                   Data-Phrasebook-Loader-YAML
version:                0.13
abstract:               Loader class for phrasebook implementations using YAML files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Carp:                   0
  Data::Phrasebook:       0.24
  YAML:                   0.35
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::Distribution:     0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  Data::Phrasebook::Loader::YAML:
    file: lib/Data/Phrasebook/Loader/YAML.pm
    version: 0.13

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Phrasebook-Loader-YAML
  repository: http://github.com/barbie/data-phrasebook-loader-yaml

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
