--- #YAML:1.0
name:                   Data-Phrasebook-Loader-YAML
version:                0.09
abstract:               This module provides a loader class for phrasebook implementations using YAML.
author:
  - Barbie <barbie@cpan.org>

license:                gpl
distribution_type:      module
installdirs:            site

requires:
  Data::Phrasebook:     0.18
  YAML:                 0.35
  Test::More:           0.47
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Meta:     0
build_requires:
  Test::More:           0.47

provides:
  Data::Phrasebook::Loader::YAML:
    file: lib/Data/Phrasebook/Loader/YAML.pm
    version: 0.09
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
